### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Yubico/yubioath-flutter#1552]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6795884174

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/3909ce5b4f70e6b6fe65972fdb3de8fe567dad83

**Comment by AdamVe** [comment]
Hi @licaon-kter, the issue is caused by wrong version of Flutter being used to build the app on F-Droid.

Correctly, the version on this line [metadata/com.yubico.yubioath.yml#L649](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.yubico.yubioath.yml#L649) should be `3.19.6`.

The F-Droid version of Yubico Authenticator is maintained by the community. If you are able to report the issue or even create a PR in the F-Droid repository, please do. If you are not able to do it, please let us know. Thanks!

**Comment by licaon-kter** [comment]
Right, can we be sure https://github.com/Yubico/yubioath-flutter/blob/main/.github/workflows/env is kept up to date so we can use the version noted?

**Comment by AdamVe** [comment]
Yes, the env file holds the correct version.

I reviewed the build steps on F-Droid and I see that it is missing the [collectLicenses task](https://github.com/Yubico/yubioath-flutter/blob/main/android/scripts/build.sh#L4-L6) from our builds. Without running that task, the app will not be able to show open source license information of used dependencies. If you have a possibility, please update that.

**Comment by AdamVe** [comment]
The error is caused because the `oss-licenses-plugin` has been removed from the build by [this prebuild](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.yubico.yubioath.yml#L610) step. One way to avoid this would be to adjust the command so that it deletes lines containing `gms` but keeps lines containing `gms.oss-licenses-plugin`:
```
sed -i -e '/gms\.oss-licenses-plugin/p;/gms/d' android/{app/build.gradle,build.gradle}
```

The command should be run in the `android/` directory.

**Comment by licaon-kter** [comment]
Updated, thanks https://gitlab.com/fdroid/fdroiddata/-/commit/3192d6d22b5c8ef174a923f344b21ce7d3565c18

**Comment by AdamVe** [comment]
That is great, thanks!!

I see that you [use](https://gitlab.com/fdroid/fdroiddata/-/commit/3192d6d22b5c8ef174a923f344b21ce7d3565c18#9d8c4e316e40d2b6e98c7b463aa915deafe114a2_627_630) `flutter@stable`. This could potentially cause build errors when flutter stable introduces breaking changes and is the reason why we are pinning a specific version.

Let us know if we can improve anything related to F-Droid.

**Comment by licaon-kter** [comment]
Scroll a bit down to, `source` then a bit lower to `git` ;)

**Comment by AdamVe** [comment]
Nice, you are using the env file 👏🏻

**Comment by licaon-kter** [comment]
@AdamVe yeah, so keep that up to date :smile_cat:

**Comment by AdamVe** [comment]
We will ;)

I see that F-Droid already provides the new version! We have a [ticket](https://github.com/Yubico/yubioath-flutter/issues/1402) for adding metadata to provide the F-Droid icon resource. @licaon-kter What would you recommend?

**Comment by licaon-kter** [comment]
> I see that F-Droid already provides the new version!

I've updated the metadata only, do read: https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client
