### ISSUE TITLE
Android App suddenly in French

### ISSUE THREAD

**Issue by maxwai** [Yubico/yubioath-flutter#1560]
Hi, with Version 7.0.0 of the Android App, the App shows up in French.

Before that the App was always in English since I have my phone in German.

If I activate the community translations it correctly changes to German, but if turned off, it defaults to French.

The correct behavior should be that the app defaults to English if the system language is not supported.

Also, as an additional note: Maybe a Setting to switch languages would be good, or use the Android feature that you can set a Language for an App directly in the system settings.

**Comment by AdamVe** [comment]
Thanks for the report. French and Japanese are now officially supported so that could be the reason for this behaviour. 

Could you see what languages you have in the System settings and in what order? The app will be displayed in the first officially supported "preferred" language. 

![55](https://github.com/Yubico/yubioath-flutter/assets/1954891/1b5d1104-86ab-405d-be9d-c3ad0b17c81f)


In the screenshot, French is the second preferred language and that will make Yubico Authenticator 7.0+ show in that language. To make it English, I need to move English on top of French. Could you try if this helps? If you don't have English in the list, please add it. If you don't have French in the list and the app shows in French than that is a bug, please let me know. After you have done changes to the language list, restart the app.

I will bring the idea for improving the language selection back to our team.
