### ISSUE TITLE
"passkey" french translation

### ISSUE THREAD

**Issue by CaseOf** [Yubico/yubioath-flutter#1570]
Hello,

The current translation in French of the word "passkey" linked below seems incorrect to me.
French is my main language and it looks like translated automatically (in bad way of this term).

It can be confusing since the translated word in French means password and not passkey.
I don’t know yet a good translation of word passkey in French.
Actually, French tech news sites just calls it "passkey" without translating it.

I think it’ll be better understood if the "passkey" word isn’t translated.
What do you think about it?

https://github.com/Yubico/yubioath-flutter/blob/efade221cd1ec3ce33bce9423b2d30d27c39fb82/lib/l10n/app_fr.arb#L463

**Comment by braathen** [comment]
Bonjour!

I think you're right that it's probably better to keep it as "passkey", thanks for pointing this out. Translations are sometimes complicated, we're still learning and investigating how we can improve the way we handle multiple languages.

**Comment by braathen** [comment]
I just wanted to let you know that the "passkey" translation has been resolved in the 7.1 version which is available now. Thank you for bringing it to our attention.

Also, while at it I'd like to mention here that we have now moved all our translations into Crowdin. From now on if you or anyone else sees any mistakes or things that could be improved, please feel free to sign-up with Crowdin and join our projects to help out with proofreading or translations. 😊  

For example, currently French is 100% translated but only 83% proofread, which means we had to do some machine translations for the newest features in order to get them into this release. Hopefully we will get this number up and in the future, with kind and generous help from people, the goal is that it should be 100% BEFORE release.

https://crowdin.com/project/yubico-authenticator
