### ISSUE TITLE
On Yubikey NFC tap does nothing

### ISSUE THREAD

**Issue by nosar77** [Yubico/yubioath-flutter#1586]
On my galaxy s23u the on tap function does nothing. The yubikey won't even scan unless I open the app then press it. Nfc is turned on the yubikey and I'm on the latest version.

**Comment by AdamVe** [comment]
Hi, thanks for reporting, this shouldn't be happening. Could you let me know the YubiKey type? If you use any phone case, could you remove it from the phone and try the app again?

**Comment by nosar77** [comment]
> Hi, thanks for reporting, this shouldn't be happening. Could you let me know the YubiKey type? If you use any phone case, could you remove it from the phone and try the app again? 

It's a yubikey 5 NFC and I have no case on my S23u.

**Comment by AdamVe** [comment]
Let’s see some other options we have to figure out what might be going on.

- When you open the app and tap the key, then open the drawer menu, can you see the following Items: Home, Accounts and Passkeys? (see the screenshot)
![Screenshot_20240619-090020](https://github.com/Yubico/yubioath-flutter/assets/1954891/1f547669-0e65-4af6-8d7d-2df4064e389d)

- In Settings (Home page -> Menu -> Settings) the On YubiKey NFC tap should be set to “Launch Yubico Authenticator”
![Screenshot_20240619-090413](https://github.com/Yubico/yubioath-flutter/assets/1954891/d6508522-83ba-4b9d-9e18-66f332a887d6)

On YubiKey 5 one can toggle applications. For the NFC Tap to work, it is important that the Yubico OTP application is enabled for NFC. (screenshot is from desktop version of Yubico Authenticator).
![image](https://github.com/Yubico/yubioath-flutter/assets/1954891/0780e729-7300-480e-842f-6c47b618899f)

When you have a chance, could you review these?

**Comment by nosar77** [comment]
Sorry for the late response, I can confirm all of this works. And it works when the app is open I can use NFC and the features work, it's either the Samsung/android messing with the ability of the key to open app or the app isn't registering the scans from the S23u. My S23u scans nfc perfectly fine with other things.

**Comment by AdamVe** [comment]
That’s unfortunate and I really would like to understand what could be going on. Here are more ideas:
- The app only reacts when the NFC tag contains `https://my.yubico.com/` prefix. This prefix can be changed in `ykman` and doing so will make the app unable to open on nfc tap.
- On Android 14 (at least on Pixel) there is a menu called “Launch via NFC” (it is hidden in Settings->Apps->Special app access->Launch via NFC). The apps listed there can be adjusted to react on nfc tap from home screen or not. Turning off Yubico Authenticator will disable the opening.
- I experienced following behavior on my Pixel - installing an extra browser such as Firefox and after that tapping the YubiKey resulted with a question “Which app should handle the NFC tap”, that is because a new app now can handle nfc taps and the users can decide. Could you try to install an extra browser and see if it has any impact?

I will try to reproduce the issue on a Samsung Galaxy 23 asap, what is your Android version?

**Comment by nosar77** [comment]
unfortunately I don't have another yubikey to test to see if mine is defective however, when i tried to use my yubikey on my wifes iphone 14 pro max, It didn't register at all as in it wouldn't scan except this time I had the app open. Is there anyway to test to know for sure before I try to return and buy another yubikey?

**Comment by nosar77** [comment]
I was looking to this prefix thing, do I need to have something configured to set use nfc NDEF to make sure the prefix is set?

**Comment by AdamVe** [comment]
I am glad that the NFC tap works for you as expected now 🥳. Let us know if you have any issues/wishes for the app, we appreciate all feedback.
