### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by martin-bussieres** [Yubico/yubioath-flutter#783]
Hi, we are looking to deploy many keys in one of our Canadian government department. We can only deploy bilingual English/French tools to our end users. What would be the options to globalize this application?

I'm ready to pitch in to translate text from English to French,

Thanks

**Comment by dainnilsson** [comment]
Hi! What is the timeframe for this deployment? I ask because we are currently working on the next major version of this app, and a lot will be changing around the technical implementation of the UI. It will probably be easier (and more future-proof) to translate the new version, but that will also require waiting a bit before it's ready.

**Comment by martin-bussieres** [comment]
Sorry for the long delay. We already deployed a few thousand yubikey and it will continue. The thing is, we want them to be the first and only MFA method for many users. Without a bilingual tool (gov of Canada law), we still need to rely on less secure methods such as phone call and sms for the onboarding of the yubikey. My department doesn't have the man power to manage Temporary Access Pass.
Again, if you need help with translation I'll be more than happy to help, I'm a dotNet dev btw.

Thanks

**Comment by dainnilsson** [comment]
Removing the `legacy` label. This should now be more feasible given the newly released 6.0 version.

**Comment by dainnilsson** [comment]
We now have a community provided translation for French in version 6.3.0 of the app.
