### ISSUE TITLE
Is Yubico Authenticator on Ubuntu Software legit?

### ISSUE THREAD

**Issue by sunknudsen** [Yubico/yubioath-flutter#892]
There are two apps on Ubuntu Software… one flagged as potentially unsafe and the other branded as released by Yubico.

The one branded as released by Yubico is at version 5.1.0… are you guys managing that one? If yes, are you planning on releasing 6.0.2 on Ubuntu Software?

**Comment by dainnilsson** [comment]
As far as I can tell, the "unsafe" one is actually the package from Debian (apt): https://packages.debian.org/unstable/utils/yubioath-desktop. As we are not the maintainer of that I can't speak for if they intend to update to 6.0 or not, but I would hope so. It's not "official" from Yubico, but it's "official" from Debian.

The other one is a Snap package of the older 5.1 version which unfortunately suffers from some technical issues due to the sandbox imposed by the Snap packaging system. We have not (yet) released a Snap package for 6.0, and I don't have a date for when or if that will happen. Our current recommendation is to use the pre-compiled Linux binary we offer for download, or a community packaged version for a specific distro.
