### ISSUE TITLE
WebAuthn credentials shown for Security Key C but not for Yubikey 5

### ISSUE THREAD

**Issue by tox1c90** [Yubico/yubioath-flutter#932]
Hi!

I have noticed a strange issue with the WebAuthn tab in Yubico Authenticator 6.0.2 (Windows Store version).
I have a Yubikey 5 NFC (F/W: 5.1.2) and a Security Key C NFC (F/W: 5.4.3), for both I added a FIDO2 PIN via Windows built-in security key settings.

When I start Yubico Authenticator (as Admin) and open the WebAuthn tab, it will only ask for the FIDO2 PIN on my Security Key C and show the registered WebAuthn credentials.
On my Yubikey 5, it does not ask for the PIN, and it shows no accounts, just "Ready to use". Even the "Change PIN" button is not offered.

![securitykeyc](https://user-images.githubusercontent.com/43222297/214687533-8694d97f-d506-4569-a535-dd3bbb50ddb8.png)
![yubikey5](https://user-images.githubusercontent.com/43222297/214687579-6c0face0-5969-40cd-8df6-26997f167745.png)

I have added both keys directly after each other to the same two account, and they are both working just fine (and in both cases, Windows is asking for the PIN when I use them to sign-in).

So what could be wrong that Yubico Authenticator does not recognized the (working) WebAuthn credentials on the Yubikey 5?

**Comment by dainnilsson** [comment]
WebAuthn/FIDO2 supports two different kind of credentials: discoverable, and non-discoverable. The non-discoverable ones aren't actually stored on a YubiKey, and will never be listable. In your case, I believe you are using discoverable credentials on both keys, which ARE stored on the YubiKey.

HOWEVER: The ability to enumerate and individually manage these discoverable credentials wasn't part of the initial specification, rather it was added later. I believe this was added to YubiKeys in version 5.2.

So while you're 5.1 YubiKey has support for storing such credentials, it does not support listing them, or deleting them on a one-by-one basis (you have to perform a full factory reset of the FIDO application to clear them out), which is why Yubico Authenticator doesn't ask you for a PIN or show any credentials.
