### ISSUE TITLE
Feature Request: Reset OATH after fixed number of password attempts

### ISSUE THREAD

**Issue by BenihanaDarkslide** [Yubico/yubioath-flutter#999]
Hello,

A feature request:
Limit the number of attempts allowed for the OATH TOTP password protocol before locking you out.

The idea is to give an option to limit the number of tries to enter the password for the OATH credentialing system. Similar to how the FIDO2 application will give you 8 tries, after which the only option left is to 'reset' the FIDO2 credentials. An optional feature like this would give peace of mind in the event that your YubiKey is stolen/misplaced.

If stolen/misplaced, one would replace the YubiKey authenticator with a new YubiKey and re-register backups of all the QR codes. Currently without the password attempt limit, it's probably best to replace the 2FA TOTP on all websites/services affected ( up to 32 ). Deactivating/re-activating TOTP 2FA can be a tedious process.

I realize this is something that would need changes at the hardware level, and I'm not sure how feasible it is. I thank you for taking the time to read this idea.

Thank you,

**Comment by dainnilsson** [comment]
Hi,

Just as you mentioned, this is something that would require protocol changes at the hardware level, not something that we could do in the app itself. Of course, if this were to change in the YubiKey, we would support it in this app as well.

One thing that I think is important to note is that since each attempt to "guess" the password needs to be sent to the YubiKey itself for verification, this severely limits the rate at which an attacker can try different passwords. Even a relatively short password should be infeasible to break in any reasonable time.

**Comment by BenihanaDarkslide** [comment]
Hello,

I appreciate you taking your time to read this and reply.

Thank you for sharing that information about the password being sent to the YubiKey, which helps limit the rate. That is pretty nifty to know, and I see what you mean by the infeasibility of breaking the password in a reasonable amount of time. :)

Thank you,

**Comment by emlun** [comment]
Do note that this of course comes with the usual caveat on passwords: a weak password could still be broken. If your password is one on a list of the 10k most common passwords, it is very easy to break. Please practice good password hygiene for your OATH password as you would for any other password.

**Comment by jagerkin** [comment]
I would like to note that someone may use the same pin on all functions of the Yubikey without realizing one of them doesn't get locked out. The app could pop up a "don't reuse this password as a PIN for FIDO/PIV/GPG" warning if nothing else.
